name:                generic-prior
version:             0.1.0.0
github:              "esennesh/generic-prior"
license:             BSD3
author:              "Eli Sennesh"
maintainer:          "esennesh@ccis.neu.edu"
copyright:           "Eli Sennesh 2018"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/esennesh/generic-prior#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  generic-prior-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - generic-prior

tests:
  generic-prior-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - generic-prior
